# Generated by Django 3.2.4 on 2021-06-06 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('airTemperature', models.FloatField(default=0)),
                ('cloudCover', models.FloatField(default=0)),
                ('gust', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('seaLevel', models.FloatField(default=0)),
                ('swellDirection', models.FloatField(default=0)),
                ('swellHeight', models.FloatField(default=0)),
                ('swellPeriod', models.FloatField(default=0)),
                ('visibility', models.FloatField(default=0)),
                ('waterTemperature', models.FloatField(default=0)),
                ('waveDirection', models.FloatField(default=0)),
                ('waveHeight', models.FloatField(default=0)),
                ('windWaveDirection', models.FloatField(default=0)),
                ('windWaveHeight', models.FloatField(default=0)),
                ('windDirection', models.FloatField(default=0)),
                ('windSpeed', models.FloatField(default=0)),
            ],
        ),
    ]
